name: Publish Package

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}

      - if: steps.cache.outputs.cache-hit != 'true'
        name: Clean Install
        run: bun install --frozen-lockfile

      - name: Build Package
        run: bun run build

      - name: Publish Package
        run: bun publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}